#!/bin/sh

# https://docling-project.github.io/docling/reference/cli/

uvx docling \
    -vv \
    --no-ocr \
    --no-force-ocr \
    --pdf-backend=pypdfium2 \
    --image-export-mode=placeholder \
    "$1"

