#! /usr/bin/python3

import sys
import re

remove = [
  'table of contents',
  'Letter from the President',
  'HISTORICAL PERSPECTIVE',
  'MISSION',
  'LIVING THE MISSION',
  'ETHOS STATEMENT',
  'index',
  'Preamble',
  'At Our Core',
  'CORE VALUES',
  'COMMITMENT TO ACADEMIC INQUIRY',
  'ACCREDITATIONS AND RELATIONSHIPS',
]

for file in sys.argv[1:]:
  text = open(file).read()

  initial_size = len(text)

  for heading in remove:
    text = re.sub(r"(#{1,6})\s*(" + heading + r")\s*\n(.*?)(?=(?:\n^#{1,6}\s)|\Z)", "", text, flags=re.I|re.M|re.DOTALL)

  text = re.sub(r"## UNIVERSITY TRUSTEES.*", "", text, flags=re.I|re.DOTALL)

  print(file, initial_size, len(text))

  print(text)
